from widgets.WeatherFrame import WeatherFrame
from widgets.ClockFrame import ClockFrame
from widgets.LocationFrame import LocationFrame
from widgets.IPFrame import IPFrame
from widgets.WeatherForecastFrame import WeatherForecastFrame
from widgets.ChromecastIndicatorFrame import ChromecastIndicatorFrame